# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "https://pic.ratherhard.com/avatar/avatar1.jpg"

enableGitInfo = true

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[frontmatter]
    lastmod = ["lastmod", ":fileModTime", ":git", "publishDate"]

[footer]
    since      = 2025
    customText = ""

[dateFormat]
    published   = "2006-01-02 15:04"
    lastUpdated = "2006-01-02 15:04"

[homeTerminal]
    prompts = [
        "Life is pwnable, but not hackable.",
        "OwO?!",
        "awmc",
        "XwX"
    ]

[sidebar]
    emoji    = "🐱"
    subtitle = "路漫漫其修远兮"
    avatar   = "https://pic.ratherhard.com/avatar/avatar1.jpg"

[randomImage]
    baseURL = "https://pic.ratherhard.com/random/"
    count   = 4

[article]
    headingAnchor = false
    math          = true
    readingTime   = true

    [article.list]
        showTags = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    # homepage = [
    #     { type = "search" },
    #     { type = "archives", params = { limit = 5 } },
    #     { type = "categories", params = { limit = 10 } },
    #     { type = "tag-cloud", params = { limit = 10 } },
    # ]
    page = [{ type = "toc" }]

[background]
    image       = "https://pic.ratherhard.com/background/kaguya.jpg"
    opacity     = 0.15
    fixed       = true
    cardOpacity = 0.60

[colorScheme]
    toggle  = true
    default = "dark"

## Comments
[comments]
    enabled  = false
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
